apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend1
  template:
    metadata:
      labels:
        app: backend1
    spec:
      containers:
        - name: backend1
          image: shoaibakhtar003/backend-todo-app:latest   
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "db-service"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "root"
            - name: DB_NAME
              value: "todo_db"
            - name: DB_PORT
              value: "3306" 